spring:
  application:
    name: product

server:
  port: 8086

management.endpoints.web.exposure.include: '*'

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

my:
  greeting: Hello
  list:
    values: One,Two,Three

app:
  name: My app
  description2: Welcome to ${app.name}

dbValues:
  connectionString: 'http://.....'
  userName: 'foo'
  password: 'truc'

db:
  connection: 'postgresql://test'
  host: 192.168.120.110
  port: 1234


management:
  health:
    hazelcast:
      enabled: false
